services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service_app
    restart: always
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "3610:3610"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: auth_service_db
    restart: always
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_auth_geosandbox
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_auth_geosandbox" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
