services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service_app
    restart: always
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    expose:
      - "3610"
    depends_on:
      db:
        condition: service_healthy
      data-cache:
        condition: service_healthy
    networks:
      - default
      - global-network-geosandbox

  db:
    image: postgres:17
    container_name: auth_service_db
    restart: always
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_auth_geosandbox
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_auth_geosandbox" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  data-cache:
    image: redis:latest
    container_name: auth_service_data_cache
    restart: always
    command: redis-server --requirepass secretredispassword
    ports:
      - "6380:6379"
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a secretredispassword ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data-cache-data:/data

volumes:
  db-data:
  data-cache-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  default:
  global-network-geosandbox:
    external: true
